[package]
name = "journal-json"
version = "0.1.0"
edition = "2021"
license = "MIT/Apache-2.0"

[dependencies]
getset = "0.1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
serde_json = "1"
