name: "Update flakes"

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # 03:15 every 1st of the month
    - cron:  '15 3 1 * *'

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@v26
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@v21
        with:
          pr-title: "Update flake.lock" # Title of PR to be created
          inputs:
            - cargo-changelog
            - crane
            - flake-utils
            - nixpkgs
            - rust-overlay

